"""agregar nombre y hora_fin a turnos fijos

Revision ID: 43a3b887cc1d
Revises: ffee2504d85f
Create Date: 2026-08-03 19:02:30.891036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a3b887cc1d'
down_revision: Union[str, Sequence[str], None] = 'ffee2504d85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turnos_fijos', sa.Column('hora_fin', sa.Time(), nullable=True))
    op.add_column('turnos_fijos', sa.Column('nombre', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turnos_fijos', 'nombre')
    op.drop_column('turnos_fijos', 'hora_fin')
    # ### end Alembic commands ###
