"""add email to admin_usuario and password_reset_token table

Revision ID: 9759f5851eac
Revises: c4e8f2a1b6d9
Create Date: 2026-08-09 00:07:32.630758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9759f5851eac'
down_revision: Union[str, Sequence[str], None] = 'c4e8f2a1b6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('admin_usuario_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_usuario_id'], ['admin_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_token'), 'password_reset_token', ['token'], unique=True)
    op.add_column('admin_usuario', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_admin_usuario_email'), 'admin_usuario', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_usuario_email'), table_name='admin_usuario')
    op.drop_column('admin_usuario', 'email')
    op.drop_index(op.f('ix_password_reset_token_token'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
