"""crear tablas iniciales

Revision ID: ffee2504d85f
Revises: 
Create Date: 2026-08-03 18:21:38.518122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffee2504d85f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_usuario_username'), 'admin_usuario', ['username'], unique=True)
    op.create_table('canchas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('alias_transferencia', sa.String(length=100), nullable=False),
    sa.Column('precio_cancha_default', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_senia_default', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hora_apertura', sa.Time(), nullable=False),
    sa.Column('hora_cierre', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloqueos_puntuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('creado_por', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_bloqueo_cancha_fecha_hora', 'bloqueos_puntuales', ['cancha_id', 'fecha', 'hora_inicio'], unique=True)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=150), nullable=False),
    sa.Column('telefono_cliente', sa.String(length=30), nullable=False),
    sa.Column('precio_cancha', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_senia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_reserva_activa_cancha_fecha_hora', 'reservas', ['cancha_id', 'fecha', 'hora_inicio'], unique=True, sqlite_where=sa.text("estado IN ('PENDIENTE', 'CONFIRMADA')"), postgresql_where=sa.text("estado IN ('PENDIENTE', 'CONFIRMADA')"))
    op.create_table('turnos_fijos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_turno_fijo_cancha_dia_hora', 'turnos_fijos', ['cancha_id', 'dia_semana', 'hora_inicio'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_turno_fijo_cancha_dia_hora', table_name='turnos_fijos')
    op.drop_table('turnos_fijos')
    op.drop_index('uq_reserva_activa_cancha_fecha_hora', table_name='reservas', sqlite_where=sa.text("estado IN ('PENDIENTE', 'CONFIRMADA')"), postgresql_where=sa.text("estado IN ('PENDIENTE', 'CONFIRMADA')"))
    op.drop_table('reservas')
    op.drop_index('uq_bloqueo_cancha_fecha_hora', table_name='bloqueos_puntuales')
    op.drop_table('bloqueos_puntuales')
    op.drop_table('configuracion_club')
    op.drop_table('canchas')
    op.drop_index(op.f('ix_admin_usuario_username'), table_name='admin_usuario')
    op.drop_table('admin_usuario')
    # ### end Alembic commands ###
